// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsTensor")>]
[<assembly: AssemblyDescriptionAttribute("FsTensor, Tensor manipulations and calculations as part of FsLab
Initialisation")>]
[<assembly: AssemblyCompanyAttribute("F# incubation space")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsTensor"
    let [<Literal>] AssemblyDescription = "FsTensor, Tensor manipulations and calculations as part of FsLab
Initialisation"
    let [<Literal>] AssemblyCompany = "F# incubation space"
    let [<Literal>] AssemblyVersion = "0.0.1"
